version: '3.3'

services:
  db:
    image: andrepinheiro/dockermysql:1.0
    container_name: mysql
    build: .
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=dbname
    volumes:
      - ./data:/var/lib/mysql
      - ./init/data:/docker-entrypoint-initdb.d
    restart: always
